name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: create release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: "Remix v${{ env.PACKAGE_VERSION }}"
          body: "See the assets to download this version and install."
          draft: false
          prerelease: false
  build-tauri:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install app dependencies and build it
        run: npm install && npm run build
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}